//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvertiserInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdvertiserInfo()
        {
            this.ADinfoes = new HashSet<ADinfo>();
        }
    
        public int advertiserid { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string emailid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADinfo> ADinfoes { get; set; }
    }
}
